CREATE USER IF NOT EXISTS 'terraform01'@'%' IDENTIFIED BY 'terraform01@4876';

GRANT ALL PRIVILEGES ON terraform01.* TO 'terraform01'@'%' IDENTIFIED BY 'terraform01@4876';

CREATE DATABASE IF NOT EXISTS terraform01;
ALTER DATABASE terraform01 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;